---
deployment:
  tasks:
    - git pull
    - export DEPLOYPATH=/home/thecoefs/public_html/pie/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R corner $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R demo $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R user $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
   
    