---
deployment:
  tasks:
    - git pull
    - export DEPLOYPATH=/home/thecoefs/pie/
    - /bin/cp -R banners $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R futura $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp aboutus.html $DEPLOYPATH
    - /bin/cp courses.html $DEPLOYPATH
    - /bin/cp Signup.html $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH   
    